import { type NextPage } from "next";
import Head from "next/head";
import { useForm } from "react-hook-form";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm<{ text: string }>();

  const summerizeMutation = api.prompts.shortSummary.useMutation();

  const onSubmit = ({ text }: { text: string }) => {
    summerizeMutation.mutate({
      text: text,
    });
  };

  return (
    <>
      <Head>
        <title>summer - GPT3 기반 Text Summarizer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#f7f6f9] to-[#2934fe]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            summer
          </h1>
          <div className="flex w-full max-w-lg flex-col">
            <form onSubmit={handleSubmit(onSubmit)}>
              <textarea
                className="h-40 w-full rounded-lg p-4 text-lg text-gray-900"
                placeholder="여기에 요약할 텍스트를 입력하세요."
                {...register("text", { required: true })}
              />
              <button
                className="mt-4 h-12 w-full rounded-lg bg-[#2934fe] text-lg font-bold text-white"
                type="submit"
              >
                요약하기
              </button>
            </form>
          </div>
          <p className="max-w-lg text-lg text-white">
            {summerizeMutation.isLoading
              ? "Loading..."
              : summerizeMutation.data?.summary}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
